library-management/libraryproject/libraryapp/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *
from .templates import *
from django.conf.urls import url, include


app_name = "libraryapp"

urlpatterns = [
    url(r'^$', book_list, name='home'),
    url(r'^books$', book_list, name='books'),
    url(r'^librarians$', list_librarians, name='librarians'),
    url(r'^$', home, name='home'),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^book/form$', book_form, name='book_form'),
    url(r'^libraries$', library_list, name='libraries'),
    url(r'^library/form$', library_form, name='library_form'),
    path('books/<int:book_id>/', book_details, name='book'),
    # path('books/<int:book_id>/', book_details, name='book')
]

library-management/libraryproject/libraryproject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from libraryapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('libraryapp.urls')),
]

library-management/libraryproject/libraryapp/models.py
from django.db import models

# Create your models here.

library-management/libraryproject/libraryapp/models/book.py
from django.db import models
from .library import Library
from .librarian import Librarian

class Book(models.Model):

    title = models.CharField(max_length=50)
    isbn = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    year_published = models.CharField(max_length=50)
    location = models.ForeignKey(Library, on_delete=models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)


    class Meta:
        verbose_name = ("")
        verbose_name_plural = ("s")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("_detail", kwargs={"pk": self.pk})

library-management/libraryproject/libraryapp/models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

library-management/libraryproject/libraryapp/models/library.py
from django.db import models

class Library(models.Model):
    title = models.CharField(max_length=50)
    address = models.CharField(max_length=50)


    class Meta:
        verbose_name = ("")
        verbose_name_plural = ("s")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("_detail", kwargs={"pk": self.pk})

library-management/libraryproject/libraryapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

library-management/libraryproject/libraryapp/views.py
from django.shortcuts import render

# Create your views here.

library-management/libraryproject/libraryapp/views/connection.py
class Connection:
    db_path = "C:/Users/Daniel/workspace/python/library-management/libraryproject/db.sqlite3"

library-management/libraryproject/libraryapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

library-management/libraryproject/libraryapp/templates/books/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ book.title }}</h1>
    <h2>By {{ book.author }}</h2>

    <div>Published in {{ book.year_published }}</div>
    <div>ISBN: {{ book.isbn }}</div>
    <form action="{% url 'libraryapp:book' book.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="actual_method" value="EDIT">
        <button>Edit</button>
    </form>
    <form action="{% url 'libraryapp:book' book.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE">
        <button>Delete</button>
    </form>
  </body>
</html>

library-management/libraryproject/libraryapp/templates/books/edit.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
  <form action="{% url 'libraryapp:book' book.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <label for="title">Title: </label>
            <input id="title" type="text" name="title" value="{{ book.title }}"></input>
        </fieldset>
        <fieldset>
            <label for="author">Author: </label>
            <input id="author" type="text" name="author" value="{{ book.author }}"></input>
        </fieldset>
        <fieldset>
            <label for="year_published">Year of publication: </label>
            <input id="year_published" type="number" name="year_published" value="{{ book.year_published }}"></input>
        </fieldset>
        <fieldset>
            <label for="isbn">ISBN: </label>
            <input id="isbn" type="text" name="isbn" value="{{ book.isbn }}"></input>
        </fieldset>

        <input type="hidden" name="actual_method" value="UPDATE">
        <button>Update</button>
    </form>
  </body>
</html>

library-management/libraryproject/libraryapp/templates/books/form.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Inventory Book</h1>


    <form action="{% url 'libraryapp:books' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="author">Author: </label>
          <input id="author" type="text" name="author">
      </fieldset>
      <fieldset>
          <label for="year_published">Year of publication: </label>
          <input id="year_published" type="number" name="year_published">
      </fieldset>
      <fieldset>
          <label for="isbn">ISBN: </label>
          <input id="isbn" type="text" name="isbn">
      </fieldset>
      <fieldset>
          <label for="location">Library: </label>
          <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                    <option value="{{ library.id }}">{{ library.title }}</option>
                {% endfor %}
          </select>
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

library-management/libraryproject/libraryapp/templates/books/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Books</h1>

    <ol>
    {% for book in all_books %}
        <li>
            <a href="{% url 'libraryapp:book' book.id %}"> {{ book.title }} </a>
            by {{book.author}} published in {{book.year_published}}
        </li>
    {% endfor %}
    </ol>
  </body>
</html>

library-management/libraryproject/libraryapp/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Nashville Library Management System</title>
</head>

<body>

    <h1>Welcome to the Nashville Library Management System</h1>

</body>

</html>

library-management/libraryproject/libraryapp/templates/librarians/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
        <li>{{ librarian.first_name }} {{ librarian.last_name }}</li>
    {% endfor %}
    </ol>
  </body>
</html>

library-management/libraryproject/libraryapp/templates/libraries/form.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Inventory Library</h1>


    <form action="{% url 'libraryapp:libraries' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="address">Address: </label>
          <input id="author" type="text" name="address">
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

library-management/libraryproject/libraryapp/templates/libraries/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Libraries</h1>

    <ol>
    {% for library in all_libraries %}
        <li>
            {{ library.title }}
            located at {{library.address}}
        </li>
    {% endfor %}
    </ol>
  </body>
</html>